
from flask import Flask, Blueprint, render_template, request, abort
import os

# Create a Blueprint with /cs as the URL prefix
norn_net_bp = Blueprint('cs', __name__, url_prefix='/cs')


@norn_net_bp.route("/")
def hello():
    return render_template("index.html")


# Create the Flask app and serve static files under the /cs prefix so
# requests like /cs/static/css/styles.css are handled by Flask.
# This ensures the stylesheet link generated by url_for('static', ...) is
# reachable when the app's routes are under the /cs blueprint prefix.
app = Flask(__name__, static_folder='static', static_url_path='/cs/static')

# Register the blueprint
app.register_blueprint(norn_net_bp)


if __name__ == "__main__":
    app.run(debug=True)
