
from flask import Flask, Blueprint, render_template, request, abort

# Create a Blueprint with /norn_net as the URL prefix
norn_net_bp = Blueprint('norn_net', __name__, url_prefix='/norn_net', template_folder='templates')


@norn_net_bp.route("/")
def hello():
    return render_template("index.html")


@norn_net_bp.route('/docs')
def docs():
    return render_template('docs.html')


# Create the Flask app and serve static files under the /cs prefix so
# requests like /cs/static/css/styles.css are handled by Flask.
# This ensures the stylesheet link generated by url_for('static', ...) is
# reachable when the app's routes are under the /norn_net blueprint prefix.
app = Flask(__name__, static_folder='static', static_url_path='/norn_net/static')

# Register the blueprint
app.register_blueprint(norn_net_bp)


@app.context_processor
def inject_globals():
    # Provide the current year to templates for footer
    from datetime import datetime
    return dict(current_year=datetime.utcnow().year)


if __name__ == "__main__":
    app.run(debug=True)
