
from flask import Flask, Blueprint, render_template, request, abort

# Create a Blueprint with /nornnet as the URL prefix
nornnet_bp = Blueprint('nornnet', __name__, url_prefix='/nornnet', template_folder='templates')


@nornnet_bp.route("/")
def hello():
    return render_template("index.html")


@nornnet_bp.route('/docs')
def docs():
    return render_template('docs.html')


# Create the Flask app and serve static files under the /cs prefix so
# requests like /cs/static/css/styles.css are handled by Flask.
# This ensures the stylesheet link generated by url_for('static', ...) is
# reachable when the app's routes are under the /nornnet blueprint prefix.
app = Flask(__name__, static_folder='static', static_url_path='/nornnet/static')

# Register the blueprint
app.register_blueprint(nornnet_bp)


@app.context_processor
def inject_globals():
    # Provide the current year to templates for footer
    from datetime import datetime
    return dict(current_year=datetime.utcnow().year)


if __name__ == "__main__":
    app.run(debug=True)
